#! /bin/sh

#Auto Start Stuff
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x spotify > /dev/null || spotify &
pgrep -x slack > /dev/null || slack &
pgrep -x copyq > /dev/null || copyq & 
~/.config/polybar/launch.sh &
~/.fehbg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^1'
bspc rule -a Spotify desktop='^10'
bspc rule -a mplayer2 state=floating
