#!/bin/bash

echo "Updating system"
paru -Syu

echo "Clearing pacman cache"
pacman_cache_space_used="$(du -sh /var/cache/pacman/pkg/)"
paccache -r
echo "Space saved: $pacman_cache_space_used"

echo "Removing orphan packages"
orphans=$(paru -Qdtq)
if [[ -n "$orphans" ]]; then
    echo "$orphans" | paru -Rns -
else
    echo "No orphan packages to remove."
fi

echo "Clearing ~/.cache"
home_cache_used="$(du -sh ~/.cache)"
rm -rf ~/.cache/
echo "Space saved: $home_cache_used"

echo "Clearing system logs"
sudo journalctl --vacuum-time=1d
