#!/bin/bash

BASE_DIR="$(pwd)"

for dir in */; do
    if [ -d "$dir" ]; then
        dir_name=$(basename "$dir")
        playlist_file="${dir_name}.m3u"

        echo "#EXTM3U" > "$playlist_file"

        for video_file in "$dir"/*.mkv "$dir"/*.mp4; do
            if [ -e "$video_file" ]; then
                video_name=$(basename "$video_file")
                echo "$BASE_DIR/$dir_name/$video_name" >> "$playlist_file"
            fi
        done
    fi
done

echo "Playlists created successfully in $BASE_DIR!"
