[bell]
animation = "Linear"
duration = 0

[bell.command]
args = ["/usr/share/sounds/freedesktop/stereo/dialog-error.oga"]
program = "paplay"

[font]
builtin_box_drawing = true
size = 8
# size = 10

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 1.0

[window.padding]
x = 15
y = 15
